### ISSUE TITLE
Create State Diagram of Socket TCP Manager Design

### ISSUE THREAD

**Issue by bama4** [bama4/simple-http-server#4]
**Description**

This ticket involves adding a state diagram for the socket_tcp_manager library.

The library should include the following:
- Handles tcp socket connections in a multithreaded way
- Has a limit on number of threads that can be used
- Has a limit on number of active connections at one time

**Prerequisites**
N/A

**Goal**
Design conveys:
- [x] How sockets will be created
- [x] How connections will be managed through multithreading
- [x] How data will be passed back and forth

**Comment by garfr** [comment]
An obvious way to implement the concurrency in this seems to be with thread pools and task queues, and it shouldn't be hard.  The other obvious option is just to have one OS thread per request but this should only be temporary due to its inefficient nature.  We could leave the number of threads in the pool to be fine tuned allowing for the kind of hard limits you are talking about.

**Comment by bama4** [comment]
I agree. There is a set number of threads in a pool, and the tasks are queued. Threads take the next task in the queue, execute that task, and then pick up the next task in the queue. So basically we would need to implement queue and thread pool types. Maybe we should make a 'utils' folder for these utility objects. It would not be one thread per connection/request in this case but rather a thread executing a task from the queue.
